### ISSUE TITLE
error 500 when the required parameter is missing

### ISSUE THREAD

**Issue by Rabid-Squirrel** [crypto-pepe/firewall-collector#30]
From config.yaml for collector:
service:
  request:
    host_header: host1
    ip_header: header

I send request without required parameter:
Request:
POST // HTTP/1.1
header: header
User-Agent: PostmanRuntime/7.29.0
Accept: */*
Postman-Token: 695c972a-c321-4282-94ad-3616c786a3f5
Host: localhost:4345
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0
 
Response:
HTTP/1.1 **500** Internal Server Error
content-length: 14
content-type: text/html; charset=utf-8
date: Wed, 08 Jun 2022 09:32:53 GMT
internal error

**Comment by lynxbyorion** [comment]
Fixed in #27

**Comment by stuffy-idler** [comment]
@Rabid-Squirrel try the new build, please, and write back about the result

**Comment by Rabid-Squirrel** [comment]
The bug is fixed. Now the code 204 is returned

**Comment by stuffy-idler** [comment]
Great!
